version: "3"

services:
  v2ray:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    container_name: ir-proxy-upstream
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "2310:2310"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
