---
- name: Ensure ping_targets variable is defined
  assert:
    that: ping_targets is defined
    fail_msg: "You must define 'ping_targets' (list of IPs to ping) when running this playbook."

- name: Ping each target IP
  shell: ping -c 2 -W 1 {{ item }}
  register: ping_result
  ignore_errors: yes
  failed_when: false
  loop: "{{ ping_targets }}"

- name: Show ping results for this server
  debug:
    msg: |
      Results for {{ inventory_hostname }}:
      {% for res in ping_result.results %}
      - {{ res.item }}: {{ 'OK' if res.rc == 0 else 'FAILED' }}
      {% endfor %} 