all:
  children:
    v2ray_servers:
      hosts:
        vps1:
          ansible_host: <VPS_IP>
          ansible_user: root
          ansible_ssh_private_key_file: <PATH-TO-YOUR-SSH_KEY>
      vars:
        # Common variables for all V2Ray servers
        v2ray_port: <PORT>
        v2ray_uuid: <UPSTREAM-UUID>
        hans_password: <HANS-PASSWORD>
        hans_subnet: "10.71.71.0"
        hans_mtu: 1450 