version: "3"

services:
  v2ray:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "127.0.0.1:1010:1010"
      - "127.0.0.1:1010:1010/udp"
      - "127.0.0.1:1110:1110"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/